default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: 'untitled-framework_development'